CREATE TABLE questions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    question TEXT NOT NULL,
    option1 VARCHAR(255),
    option2 VARCHAR(255),
    option3 VARCHAR(255),
    option4 VARCHAR(255),
    correct_option INT NOT NULL
);

INSERT INTO questions (question, option1, option2, option3, option4, correct_option) VALUES
('What is the capital of India?', 'Mumbai', 'Delhi', 'Kolkata', 'Chennai', 2),
('Who is known as the Father of the Nation in India?', 'Subhash Chandra Bose', 'Mahatma Gandhi', 'Jawaharlal Nehru', 'Bhagat Singh', 2),
('Which planet is known as the Red Planet?', 'Earth', 'Mars', 'Venus', 'Jupiter', 2),
('Which gas is essential for breathing?', 'Nitrogen', 'Carbon Dioxide', 'Oxygen', 'Hydrogen', 3),
('What is the largest mammal?', 'Elephant', 'Blue Whale', 'Giraffe', 'Hippopotamus', 2),
('Who wrote "Romeo and Juliet"?', 'Leo Tolstoy', 'William Shakespeare', 'Mark Twain', 'Charles Dickens', 2),
('What is H2O commonly known as?', 'Salt', 'Water', 'Hydrogen', 'Oxygen', 2),
('Which country invented paper?', 'India', 'Egypt', 'China', 'Japan', 3),
('What is the smallest prime number?', '0', '1', '2', '3', 3),
('Which organ pumps blood?', 'Lungs', 'Kidney', 'Brain', 'Heart', 4),
('Which continent is the largest?', 'Africa', 'Asia', 'Europe', 'Australia', 2),
('Which animal is known as the Ship of the Desert?', 'Camel', 'Horse', 'Elephant', 'Goat', 1),
('In which direction does the sun rise?', 'North', 'South', 'East', 'West', 3),
('Who invented the light bulb?', 'Albert Einstein', 'Isaac Newton', 'Thomas Edison', 'Nikola Tesla', 3),
('Which country is known as the Land of Rising Sun?', 'China', 'Japan', 'Korea', 'Thailand', 2),
('What is 5 × 6?', '25', '30', '35', '36', 2),
('Which is the longest river in the world?', 'Amazon', 'Nile', 'Ganga', 'Yangtze', 2),
('Which festival is known as the Festival of Lights?', 'Holi', 'Diwali', 'Eid', 'Christmas', 2),
('How many states are there in India?', '28', '29', '27', '26', 1),
('Which is the largest ocean?', 'Atlantic', 'Pacific', 'Indian', 'Arctic', 2),
('Who discovered gravity?', 'APJ Abdul Kalam', 'Einstein', 'Isaac Newton', 'Galileo', 3),
('What is the freezing point of water?', '0°C', '10°C', '100°C', '32°C', 1),
('Which bird cannot fly?', 'Sparrow', 'Eagle', 'Penguin', 'Crow', 3),
('Which is the fastest land animal?', 'Tiger', 'Lion', 'Cheetah', 'Leopard', 3),
('Which is the national flower of India?', 'Lotus', 'Rose', 'Sunflower', 'Jasmine', 1),
('How many days are there in a leap year?', '365', '366', '364', '360', 2),
('What is the capital of France?', 'Berlin', 'Madrid', 'Paris', 'London', 3),
('Which metal is liquid at room temperature?', 'Aluminum', 'Mercury', 'Iron', 'Copper', 2),
('Which organ is responsible for filtering blood?', 'Heart', 'Liver', 'Kidney', 'Lungs', 3),
('Who painted the Mona Lisa?', 'Van Gogh', 'Pablo Picasso', 'Leonardo da Vinci', 'Michelangelo', 3),
('Who is the author of "Harry Potter"?', 'George RR Martin', 'JK Rowling', 'Rick Riordan', 'Chetan Bhagat', 2),
('Which planet is closest to the Sun?', 'Mercury', 'Venus', 'Earth', 'Mars', 1),
('What is the boiling point of water?', '100°C', '90°C', '50°C', '200°C', 1),
('Which is the smallest continent?', 'Australia', 'Europe', 'South America', 'Africa', 1),
('Which country has the Taj Mahal?', 'India', 'Pakistan', 'Nepal', 'Bangladesh', 1),
('How many colors are there in a rainbow?', '5', '6', '7', '8', 3),
('What is 9 × 9?', '72', '81', '90', '99', 2),
('Which vitamin is known as the Sunshine Vitamin?', 'Vitamin A', 'Vitamin B', 'Vitamin C', 'Vitamin D', 4),
('Which animal is the king of the jungle?', 'Elephant', 'Lion', 'Tiger', 'Leopard', 2),
('What is the main source of energy?', 'Sun', 'Air', 'Water', 'Earth', 1),
('Which blood group is universal donor?', 'A', 'B', 'AB', 'O Negative', 4),
('Which is the biggest planet?', 'Earth', 'Jupiter', 'Saturn', 'Uranus', 2),
('What is the national game of India?', 'Hockey', 'Cricket', 'Football', 'Kabaddi', 1),
('Which is the tallest mountain in the world?', 'K2', 'Kangchenjunga', 'Mount Everest', 'Nanga Parbat', 3),
('Who is the first Prime Minister of India?', 'Gandhi', 'Sardar Patel', 'Nehru', 'Rajendra Prasad', 3),
('Which device is used to measure temperature?', 'Barometer', 'Thermometer', 'Hygrometer', 'Ammeter', 2),
('Which is the most spoken language in the world?', 'Hindi', 'English', 'Spanish', 'Mandarin Chinese', 4),
('Who invented the telephone?', 'Einstein', 'Alexander Graham Bell', 'Newton', 'Tesla', 2),
('How many bones are in the human body?', '208', '206', '210', '205', 2);

